// Unity Build Uber File generated by CMake
// This file is auto generated, do not manually edit it.

#include <StdAfx.h>
#include <C:/Users/Borges/Documents/CRYENGINE Projects/CryAdventure/Code/GamePlugin.cpp>

